// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7JU0YkXSnr45eT_NdyHlBenrnFLLYNOA',
    appId: '1:137490242625:web:316cfb87b4404c10783ac0',
    messagingSenderId: '137490242625',
    projectId: 'no-more-waste-7306f',
    authDomain: 'no-more-waste-7306f.firebaseapp.com',
    storageBucket: 'no-more-waste-7306f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD8PZt1-tm4PDG7M0f1F1CxPcJGm0Tu1s',
    appId: '1:137490242625:android:b6ef2994fc0204be783ac0',
    messagingSenderId: '137490242625',
    projectId: 'no-more-waste-7306f',
    storageBucket: 'no-more-waste-7306f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCITPmV5OZkcT0gSWgbdn2QoXGT0_Li2P4',
    appId: '1:137490242625:ios:3ee35290d2737685783ac0',
    messagingSenderId: '137490242625',
    projectId: 'no-more-waste-7306f',
    storageBucket: 'no-more-waste-7306f.appspot.com',
    iosBundleId: 'com.example.noMoreWaste',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCITPmV5OZkcT0gSWgbdn2QoXGT0_Li2P4',
    appId: '1:137490242625:ios:b608d57438ca224f783ac0',
    messagingSenderId: '137490242625',
    projectId: 'no-more-waste-7306f',
    storageBucket: 'no-more-waste-7306f.appspot.com',
    iosBundleId: 'com.example.noMoreWaste.RunnerTests',
  );
}
